# Facebook (+ Wit)
ACCESS_TOKEN = 'EAAKrb2ATw1YBAD2ooWiWUMco3HJmtgClIHgJQrovi2FvHrfxi97dWuyijZBomDoYAZAcBlo9TjdgNtqGqZBNZBUDghKDXcEsNMT31VxyeB3sqOuxDNYZA0hkKMHe3zlYJzX9sWQFwPjTolpFZA3wiqX5JUbV1I7mZAc87H61XZAAOgZDZD'
VERIFY_TOKEN = 'Minorproject'
WIT_AI_ACCESS_TOKEN = 'IKJJJYYVR3X672DHFVS7U7C4L2MQSS2P'

# Offline data sources
FACTS_SOURCE_FILE = 'data/facts1.json'
JOKES_SOURCE_FILE = 'data/jokes1.json'
QUOTES_SOURCE_FILE = 'data/quotes1.json'
HELP = 'data/help.json'
COIN = 'data/coin.json'
DICE = 'data/dice.json'
DICTIONARY = 'data/dictionary.json'
HOROSCOPE = 'data/horoscope.json'
MOTIVATIONS = 'data/motivations.json'
NEWS = 'data/news.json'
SCORES = 'data/scores.json'
VIDEOS = 'data/videos.json'
ZOMATO = 'data/zomato.json'



# Access token files
SPOTIFY_TOKEN_FILE = 'tokens/spotify_token.json'

# API Keys
GOODREADS_ACCESS_TOKEN = 'Pn9BeG86056TkijDI92ug'
GOOGLE_URL_SHORTENER_API_KEY = '<<GOOGLE_URL_SHORTENER_API_KEY>>'
MAPQUEST_CONSUMER_KEY = 'SXuIKt8g1lWZ1RVIRmPJet89eqDsMrGq'
MUSIXMATCH_API_KEY = 'e1002d1fd948c924f38f5797d2a53719'
NEWS_API_KEY = '7b4b05a6e5ab4eb4975bd242cff1d32b'
SCORES_API_KEY= 'M3IbPXwsFOfLCpMSxEzEL265y6k2'
OPEN_WEATHER_MAP_ACCESS_TOKEN = '6501df2e85134066b1afda72215a767f'
SPOTIFY_API_KEY = '<<SPOTIFY_API_KEY>>'
TIME_ZONE_DB_API_KEY = '<<TIME_ZONE_DB_API_KEY>>'
TMDB_API_KEY = '<<TMDB_API_KEY>>'
WORDS_API_KEY = '<<WORDS_API_KEY>>'
YOUTUBE_DATA_API_KEY = 'AIzaSyD12KRy2iY9H9q4pAvsRhNeJJuSHyG5rwU'
ZODIAC_API_KEY='cf5463916fdd1cfa5b96889ec2590621'

# Local Testing
WIT_LOCAL_DATA = 'local/wit.json'
